#  -------------------------------------------------------------------------  #
# Wool Wires Config. (this file is automatically regenerated upon deletion)   #
#  -------------------------------------------------------------------------  #
#                                                                             #
# InputColor: <color> = The color of wool you want to act as input for wires. #
#                       This color won't be available for use as a wire.      #
#                                                                             #
# Wires:                                                                      #
#    Default: = The default settings all wires will use unless specified.     #
#        MaxSize: '<number>' = The maximum number of blocks this wire can be. #
#        Type: '<number>' = The type of wire; 0 for normal, 1 for inverse.    #
#        Allowed: All = All controllable blocks can be controlled.            #
#        Allowed: = Only specified blocks can be controlled by the wire.      #
#            - Lever                                                          #
#            - Note_Block                                                     #
#            - Dispenser                                                      #
#    <color>: same functionality as default except it overrides default.      #
#                                                                             #
#  -------------------------------------------------------------------------  #
InputColor: Brown
Wires:
    Default:
        MaxSize: 1024
        Type: 0
        Allowed: All
    Orange:
        Type: 1
        Allowed:
            - Glowstone
            - Glass
            - Lever
            - Note_Block